server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto es lo que arregla el router de React
        try_files $uri $uri/ /index.html; 
    }
}