FROM python:3.12.3-slim

# Evita que Python genere archivos .pyc y permite ver logs en tiempo real
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Directorio de trabajo
WORKDIR /app

COPY Pool_manager/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar carpeta Shared y servicio especifico
COPY Shared/ ./Shared/
COPY Pool_manager/ ./Pool_manager/

ENV PYTHONPATH="/app"

CMD ["python", "-m", "Pool_manager.app"]