  worker_cpu:
    image: sdyp-worker-cpu:latest
    build:
      context: ..
      dockerfile: Worker-cpu/Dockerfile
    profiles:
      - workers
    depends_on:
      - rabbitmq
      - coordinador
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=grupo03
      - RABBIT_PASS=grupo03
      - ENDPOINT_COORDINADOR=http://coordinador:5000/tarea_worker
      - COORDINADOR_URL=http://coordinador:5000
      - WORKER_ID=worker-cpu-auto
