services:
  worker_cpu:
    image: sdyp-worker-cpu:latest
    build:
      context: ..
      dockerfile: Worker-cpu/Dockerfile
    container_name: sdyp-worker-cpu
    environment:
      RABBIT_HOST: ${RABBIT_HOST:?Definir RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT:-5672}
      RABBIT_USER: ${RABBIT_USER:?Definir RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS:?Definir RABBIT_PASS}
      ENDPOINT_COORDINADOR: ${ENDPOINT_COORDINADOR:?Definir ENDPOINT_COORDINADOR}
      COORDINADOR_URL: ${COORDINADOR_URL:?Definir COORDINADOR_URL}
      WORKER_ID: ${WORKER_ID:-worker-cpu-local}
      WORKER_API_TOKEN: ${WORKER_API_TOKEN:?Definir WORKER_API_TOKEN}
