services:
  worker:
    build: .
    container_name: mining_worker_gpu
    restart: always
    gpus: all
    environment:
      RABBIT_HOST: 34.150.250.236
      RABBIT_PORT: 5672
      RABBIT_USER: grupo03
      RABBIT_PASS: grupo03
      ENDPOINT_COORDINADOR: https://unlucoin.info/api/tarea_worker
      COORDINADOR_URL: https://unlucoin.info/api
      GPU_BATCH_SIZE: 10000000
