services:
  worker:
    build: .
    container_name: mining_worker_gpu
    restart: always
    gpus: all
    environment:
      RABBIT_HOST: ${RABBIT_HOST:?Definir RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT:-5672}
      RABBIT_USER: ${RABBIT_USER:?Definir RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS:?Definir RABBIT_PASS}
      ENDPOINT_COORDINADOR: ${ENDPOINT_COORDINADOR:?Definir ENDPOINT_COORDINADOR}
      COORDINADOR_URL: ${COORDINADOR_URL:?Definir COORDINADOR_URL}
      GPU_BATCH_SIZE: ${GPU_BATCH_SIZE:-10000000}
      WORKER_ID: ${WORKER_ID:-worker-gpu-local}
