apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-processor
  labels:
    app: block-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: block-processor
  template:
    metadata:
      labels:
        app: block-processor
    spec:
      containers:
        - name: block-processor
          image: josuegaticaodato/coordinador:latest
          imagePullPolicy: Always
          command: ["python", "-m", "Coordinador.processor"]

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          env:
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_USER
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_PASS
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD