cluster_formation.peer_discovery_backend = classic_config

cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-0
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-1
cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq-2

default_queue_type = quorum
quorum_queue.initial_cluster_size = 3

raft.wal_max_size_bytes = 64000000